name: Publish to WinGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release to publish'
        required: true
        default: 'v2.5.0'  # Optional: You can set a default version 

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish to WinGet (.exe)
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: NomanDhoni.BlinkEye  # Replace with your app identifier
          release-tag: ${{ github.event.inputs.version }}  # Access version input
          installers-regex: '\.exe$'  # Only .exe files
          token: ${{ secrets.WINGET_TOKEN_BLINK_EYE }}
          
      - name: Publish to WinGet (.msi)
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: NomanDhoni.BlinkEye  # Replace with your app identifier
          release-tag: ${{ github.event.inputs.version }}  # Access version input
          installers-regex: '\.msi$'  # Only .msi files
          token: ${{ secrets.WINGET_TOKEN_BLINK_EYE }}

